### ISSUE TITLE
Create a todo.md file for easier contributing to the crate

### ISSUE THREAD

**Issue by AlvinKuruvilla** [Catman155/cronjob#2]
This crate is cool, I was thinking of working on a project like this, but since you have this it would be nice to be able to contribute to the repo

**Comment by Catman155** [comment]
Hi, sorry to get back to you this late, but I don't really have new ideas to implement. It should work as supposed to.

**Comment by Catman155** [comment]
Added todo.md with some ideas that could improve cronjob. closing this issue
